# Generated by Django 4.2.20 on 2025-04-23 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('ingredients', models.CharField(help_text='Enter the ingredients, seperated by a comma', max_length=225)),
                ('cooking_time', models.IntegerField(help_text='Time in minutes')),
            ],
        ),
    ]
