# Generated by Django 4.2.20 on 2025-05-14 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_difficulty_recipe_image_recipe_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, default='recipe_images/default_img.jpg', null=True, upload_to='recipe_images/'),
        ),
    ]
